spring:
  application:
    name: springboot-restapi
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${{ secrets.DB_URL }}
    username: ${{ secrets.DB_USERNAME }}
    password: ${{ secrets.DB_PASSWORD }}
  # jpa config
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8080
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: classpath:/productimgs/

# Logging Level
logging:
  level:
    root: info

## 이미지 저장할 위치와 응답할 때 이미지 주소 세팅함
image:
  ## WebConfig에 세팅
  add-resource-locations: classpath:/static/productimgs/
  add-resource-handler: /productimgs/**

  image-dir: src/main/resources/static/productimgs
  image-url: ${{ secrets.IMAGE_URL }}
jwt:
  key: ${{ secrets.JWT_SECRET_KEY }}
  time: 1800000
